### ISSUE TITLE
MQTT Reconnect

### ISSUE THREAD

**Issue by NellicusLabs** [metrafonic/asyncio-vedirect-mqtt#1]
Any chance you will be adding the functionality to reconnect to MQTT when the connection is lost?

**Comment by metrafonic** [comment]
> Any chance you will be adding the functionality to reconnect to MQTT when the connection is lost?

Hi!
Yes I'll try adding that within the next 24h

**Comment by metrafonic** [comment]
Fixed in latest tag.
