### ISSUE TITLE
Error when trying to set as system service

### ISSUE THREAD

**Issue by Wolfillo** [metrafonic/asyncio-vedirect-mqtt#3]
Hi!

First of all, thank you for the devolpment, I found it very usefull.

I have a problem setting the ve-mqtt as system service. This is my ve-mqtt service:
[Unit]
Description=VE.Direct over MQTT
After=multi-user.target

[Service]
Type=simple
ExecStart=ve-mqtt --tty /dev/serial0 --device BlueSolar-TEST --broker 10.10.10.114 --port 1883 --username mqtt_user -->Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target

It gives me error 203, but it works when I do it manually. Any ideas?

Thank you.

**Comment by metrafonic** [comment]
Hi!
Im glad you find the software useful!
As for your issue, i notice the ExecStart line is slightly malformed, as it ends with the Restart=on-failure in the one you posted.
You should be able to replace the ExecStart value with the one that runs fine in your command line.
Remember to reload and restart the daemon.

**Comment by metrafonic** [comment]
Glad you got it working!

**Comment by metrafonic** [comment]
Get the full path of `ve-direct` by typing `which ve-direct`, and use the whole path in the execStart command:

For example:
```
ExecStart=/home/user/.local/bin/ve-mqtt --tty /dev/serial0 --device BlueSolar-TEST --broker 10.10.10.114 --port 1883 --username mqtt_user --password mqttpassword
```
Its because the software is installed by a different user that what systemctl uses

**Comment by Wolfillo** [comment]
Hi! Thanks for the reply. By typing` which ve-direct` it won't return anything. Typing `whereis ve-direct` also does nothing.

I already tried with `whereis ve-mqtt` to get the full path, and then I used it like the example you give me. 

But when I do this, I get this message when starting the service:

`ExecStart=/home/pi/.local/bin/ve-mqtt --tty /dev/serial0 --device BlueSolar-TEST --broker 10.10.10.114 --port 1883 --username mqtt_user --password mqttpassword`

```
Oct 03 09:23:52 pizerosolarsice systemd[1]: Started VE.Direct over MQTT.
Oct 03 09:23:53 pizerosolarsice ve-mqtt[1019]: Traceback (most recent call last):
Oct 03 09:23:53 pizerosolarsice ve-mqtt[1019]:   File "/home/pi/.local/bin/ve-mqtt", line 5, in <module>
Oct 03 09:23:53 pizerosolarsice ve-mqtt[1019]:     from asyncio_vedirect_mqtt.__main__ import main
Oct 03 09:23:53 pizerosolarsice ve-mqtt[1019]: ModuleNotFoundError: No module named 'asyncio_vedirect_mqtt'
Oct 03 09:23:53 pizerosolarsice systemd[1]: ve-mqtt.service: Main process exited, code=exited, status=1/FAILURE
Oct 03 09:23:53 pizerosolarsice systemd[1]: ve-mqtt.service: Failed with result 'exit-code'.
Oct 03 09:23:58 pizerosolarsice systemd[1]: ve-mqtt.service: Scheduled restart job, restart counter is at 1.
Oct 03 09:23:58 pizerosolarsice systemd[1]: Stopped VE.Direct over MQTT.
Oct 03 09:23:58 pizerosolarsice systemd[1]: Started VE.Direct over MQTT.
Oct 03 09:23:58 pizerosolarsice ve-mqtt[1022]: Traceback (most recent call last):
Oct 03 09:23:58 pizerosolarsice ve-mqtt[1022]:   File "/home/pi/.local/bin/ve-mqtt", line 5, in <module>
Oct 03 09:23:58 pizerosolarsice ve-mqtt[1022]:     from asyncio_vedirect_mqtt.__main__ import main
Oct 03 09:23:58 pizerosolarsice ve-mqtt[1022]: ModuleNotFoundError: No module named 'asyncio_vedirect_mqtt'
Oct 03 09:23:58 pizerosolarsice systemd[1]: ve-mqtt.service: Main process exited, code=exited, status=1/FAILURE
Oct 03 09:23:58 pizerosolarsice systemd[1]: ve-mqtt.service: Failed with result 'exit-code'.
```

It's like it's not getting the arguments, but I'm not sure.

**Comment by metrafonic** [comment]
Try add this to the `[Service]` part of the systemctl config
```
User=pi
Group=pi
```
Otherwise you could also run the same installation as you did earlier, but via the root user

**Comment by Wolfillo** [comment]
Perfect, it works now!

Many many thanks!

**Comment by metrafonic** [comment]
Glad to be of help! I'll update the README.md too
